apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: fiap-cloud-games
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'payments-api'
        metrics_path: /metrics
        static_configs:
          - targets: ['payments-api:80']

      - job_name: 'users-api'
        metrics_path: /metrics
        static_configs:
          - targets: ['users-api:80']

      - job_name: 'games-api'
        metrics_path: /metrics
        static_configs:
          - targets: ['games-api:80']

      - job_name: 'gateway-api'
        metrics_path: /metrics
        static_configs:
          - targets: ['gateway-api:80']
