apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-consumer-config
  namespace: fiap-cloud-games
data:
  RabbitMq__Host: "rabbitmq"
  RabbitMq__Queue: "payments.requested"
  ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=gamesdb;Username=admin;Password=123456"
