apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-consumer
  namespace: fiap-cloud-games
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-consumer
  template:
    metadata:
      labels:
        app: payments-consumer
    spec:
      containers:
        - name: payments-consumer
          image: andresaporito/payments-consumer:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: payments-consumer-config
            - secretRef:
                name: payments-consumer-secret
