apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-api-config
  namespace: fiap-cloud-games
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:8080"

  USERS_API_URL: "http://users-api"
  GAMES_API_URL: "http://games-api"
  PAYMENTS_API_URL: "http://payments-api"
